version: '3'

services:
  app:
    build: ./
    container_name: backend_flask
    restart: unless-stopped
    volumes:
      - ./backend:/backend
    command: gunicorn main:"create_app()" -b 0.0.0.0:5000 --reload
    ports:
      - "5000:5000"