version: '3'

services:
  frontend:
    build: ./frontend/
    container_name: frontend_react
    restart: unless-stopped
    ports:
      - "3000:80"
  
  backend:
    build: ./backend/
    container_name: backend_flask
    restart: unless-stopped
    volumes:
      - ./backend:/backend
    command: python main.py
    ports:
      - "5000:5000"
    depends_on:
      - frontend
